In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('neos.csv')

/tmp/ipykernel_2946/488388308.py:1: DtypeWarning: Columns (4,5,16,23,24,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('neos.csv')

In [3]:
df.head()

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,G,...,n_obs_used,n_del_obs_used,n_dop_obs_used,condition_code,rms,two_body,A1,A2,A3,DT
0,a0000433,2000433,433 Eros (A898 PA),433,Eros,NaN,Y,N,10.4,0.46,...,8767,4.0,2.0,0.0,0.28397,NaN,NaN,NaN,NaN,NaN
1,a0000719,2000719,719 Albert (A911 TB),719,Albert,NaN,Y,N,15.5,NaN,...,1874,NaN,NaN,0.0,0.39148,NaN,NaN,NaN,NaN,NaN
2,a0000887,2000887,887 Alinda (A918 AA),887,Alinda,NaN,Y,N,13.8,-0.12,...,1424,NaN,NaN,0.0,0.48159,NaN,NaN,NaN,NaN,NaN
3,a0001036,2001036,1036 Ganymed (A924 UB),1036,Ganymed,NaN,Y,N,9.4,0.30,...,6249,0.0,1.0,0.0,0.38525,NaN,NaN,NaN,NaN,NaN
4,a0001221,2001221,1221 Amor (1932 EA1),1221,Amor,NaN,Y,N,17.7,NaN,...,540,NaN,NaN,0.0,0.45568,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.iloc[0].